name: Build & Publish Release

on: [workflow_dispatch]

jobs:
  BuildAndPublish:
    runs-on: windows-latest

    steps:
    
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        source-url: https://nuget.pkg.github.com/SephDB/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Build FontStashSharp
      run: dotnet build build\FontStashSharp.sln --configuration Release
    - name: Build FontStashSharp.MonoGame
      run: dotnet build build\FontStashSharp.MonoGame.sln --configuration Release
    - name: Build FontStashSharp.Stride
      run: dotnet build build\FontStashSharp.Stride.sln --configuration Release
    - name: Build FontStashSharp.KNI
      run: dotnet build build\FontStashSharp.KNI.sln --configuration Release
    - name: Test
      run: dotnet test build\FontStashSharp.MonoGame.sln
    - name: Publish FontStashSharp to NuGet
      run: dotnet nuget push src\FontStashSharp\bin\Release\FontStashSharp.*.nupkg
      continue-on-error: true
    - name: Publish FontStashSharp.MonoGame to NuGet
      run: dotnet nuget push src\XNA\bin\MonoGame\Release\FontStashSharp.MonoGame.*.nupkg
      continue-on-error: true
    - name: Publish FontStashSharp.Stride to NuGet
      run: dotnet nuget push src\XNA\bin\Stride\Release\FontStashSharp.Stride.*.nupkg
      continue-on-error: true
    - name: Publish FontStashSharp.KNI to NuGet
      run: dotnet nuget push src\XNA\bin\KNI\Release\FontStashSharp.KNI.*.nupkg
      continue-on-error: true
